apiVersion: external-secrets.io/v1alpha1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.storeName }}
spec:
  # provider field contains the configuration to access the provider
  # which contains the secret exactly one provider must be configured.
  provider:
    vault:
      server: {{ .Values.provider.vault.server }}
      # Path is the mount path of the Vault KV backend endpoint
      path: {{ .Values.provider.vault.path }}
      # Version is the Vault KV secret engine version.
      # This can be either "v1" or "v2", defaults to "v2"
      version: {{ .Values.provider.vault.version }}
      # vault enterprise namespace: https://www.vaultproject.io/docs/enterprise/namespaces
      #   namespace: "a-team"
      #   # base64 encoded string of certificate
      #   caBundle: "..."
      #   # Instead of caBundle you can also specify a caProvider
      #   # this will retrieve the cert from a Secret or ConfigMap
      #   caProvider:
      #     # Can be Secret or ConfigMap
      #     type: "Secret"
      #     # This is mandatory for ClusterSecretStore and not relevant for SecretStore
      #     namespace: "my-cert-secret-namespace"
      #     name: "my-cert-secret"
      #     key: "cert-key"
      auth:
        # points to a secret that contains a vault token
        # https://www.vaultproject.io/docs/auth/token
        tokenSecretRef:
          name: {{ .Values.provider.vault.auth.tokenSecretRef.name }}
          namespace: {{ .Values.provider.vault.auth.tokenSecretRef.namespace }}
          key: {{ .Values.provider.vault.auth.tokenSecretRef.key }}
